import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

// Components
import { BackgroundNoSsr } from '@/components/background';
import { classNames } from '@/tools/css_tools';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='flex h-screen w-screen'>
      <body className={classNames(
        inter.className,
        'flex h-full w-full',
      )}>
        <BackgroundNoSsr className={
          classNames(
            'flex flex-col',
            'h-full w-full',
          )
        }>
          {children}
        </BackgroundNoSsr>
      </body>
    </html>
  )
}
